/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as EditProfileRouteImport } from './routes/edit-profile'
import { Route as ExploreMatchesRouteImport } from './routes/explore-matches'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchesReadyRouteImport } from './routes/matches-ready'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as ProfileSetupStep2RouteImport } from './routes/profile-setup-step2'
import { Route as QuestionRouteImport } from './routes/question'
import { Route as QuestionnaireHubRouteImport } from './routes/questionnaire-hub'
import { Route as QuestionnaireIntroRouteImport } from './routes/questionnaire-intro'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentProfileRouteImport } from './routes/student-profile'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const EditProfileRoute = EditProfileRouteImport.update({
  id: '/edit-profile',
  path: '/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMatchesRoute = ExploreMatchesRouteImport.update({
  id: '/explore-matches',
  path: '/explore-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesReadyRoute = MatchesReadyRouteImport.update({
  id: '/matches-ready',
  path: '/matches-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupStep2Route = ProfileSetupStep2RouteImport.update({
  id: '/profile-setup-step2',
  path: '/profile-setup-step2',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionRoute = QuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireHubRoute = QuestionnaireHubRouteImport.update({
  id: '/questionnaire-hub',
  path: '/questionnaire-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireIntroRoute = QuestionnaireIntroRouteImport.update({
  id: '/questionnaire-intro',
  path: '/questionnaire-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student-profile',
  path: '/student-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRoute
  '/edit-profile': typeof EditProfileRoute
  '/explore-matches': typeof ExploreMatchesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/matches-ready': typeof MatchesReadyRoute
  '/my-profile': typeof MyProfileRoute
  '/notifications': typeof NotificationsRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/profile-setup-step2': typeof ProfileSetupStep2Route
  '/question': typeof QuestionRoute
  '/questionnaire-hub': typeof QuestionnaireHubRoute
  '/questionnaire-intro': typeof QuestionnaireIntroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/student-profile': typeof StudentProfileRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRoute
  '/edit-profile': typeof EditProfileRoute
  '/explore-matches': typeof ExploreMatchesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/matches-ready': typeof MatchesReadyRoute
  '/my-profile': typeof MyProfileRoute
  '/notifications': typeof NotificationsRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/profile-setup-step2': typeof ProfileSetupStep2Route
  '/question': typeof QuestionRoute
  '/questionnaire-hub': typeof QuestionnaireHubRoute
  '/questionnaire-intro': typeof QuestionnaireIntroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/student-profile': typeof StudentProfileRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/communities': typeof CommunitiesRoute
  '/edit-profile': typeof EditProfileRoute
  '/explore-matches': typeof ExploreMatchesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/matches-ready': typeof MatchesReadyRoute
  '/my-profile': typeof MyProfileRoute
  '/notifications': typeof NotificationsRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/profile-setup-step2': typeof ProfileSetupStep2Route
  '/question': typeof QuestionRoute
  '/questionnaire-hub': typeof QuestionnaireHubRoute
  '/questionnaire-intro': typeof QuestionnaireIntroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/student-profile': typeof StudentProfileRoute
  '/verify-email': typeof VerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/communities'
    | '/edit-profile'
    | '/explore-matches'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/matches-ready'
    | '/my-profile'
    | '/notifications'
    | '/profile-setup'
    | '/profile-setup-step2'
    | '/question'
    | '/questionnaire-hub'
    | '/questionnaire-intro'
    | '/reset-password'
    | '/signup'
    | '/student-profile'
    | '/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/communities'
    | '/edit-profile'
    | '/explore-matches'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/matches-ready'
    | '/my-profile'
    | '/notifications'
    | '/profile-setup'
    | '/profile-setup-step2'
    | '/question'
    | '/questionnaire-hub'
    | '/questionnaire-intro'
    | '/reset-password'
    | '/signup'
    | '/student-profile'
    | '/verify-email'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/communities'
    | '/edit-profile'
    | '/explore-matches'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/matches-ready'
    | '/my-profile'
    | '/notifications'
    | '/profile-setup'
    | '/profile-setup-step2'
    | '/question'
    | '/questionnaire-hub'
    | '/questionnaire-intro'
    | '/reset-password'
    | '/signup'
    | '/student-profile'
    | '/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CommunitiesRoute: typeof CommunitiesRoute
  EditProfileRoute: typeof EditProfileRoute
  ExploreMatchesRoute: typeof ExploreMatchesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MatchesReadyRoute: typeof MatchesReadyRoute
  MyProfileRoute: typeof MyProfileRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  ProfileSetupStep2Route: typeof ProfileSetupStep2Route
  QuestionRoute: typeof QuestionRoute
  QuestionnaireHubRoute: typeof QuestionnaireHubRoute
  QuestionnaireIntroRoute: typeof QuestionnaireIntroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StudentProfileRoute: typeof StudentProfileRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-profile': {
      id: '/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof EditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-matches': {
      id: '/explore-matches'
      path: '/explore-matches'
      fullPath: '/explore-matches'
      preLoaderRoute: typeof ExploreMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches-ready': {
      id: '/matches-ready'
      path: '/matches-ready'
      fullPath: '/matches-ready'
      preLoaderRoute: typeof MatchesReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup-step2': {
      id: '/profile-setup-step2'
      path: '/profile-setup-step2'
      fullPath: '/profile-setup-step2'
      preLoaderRoute: typeof ProfileSetupStep2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question': {
      id: '/question'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof QuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-hub': {
      id: '/questionnaire-hub'
      path: '/questionnaire-hub'
      fullPath: '/questionnaire-hub'
      preLoaderRoute: typeof QuestionnaireHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-intro': {
      id: '/questionnaire-intro'
      path: '/questionnaire-intro'
      fullPath: '/questionnaire-intro'
      preLoaderRoute: typeof QuestionnaireIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-profile': {
      id: '/student-profile'
      path: '/student-profile'
      fullPath: '/student-profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CommunitiesRoute: CommunitiesRoute,
  EditProfileRoute: EditProfileRoute,
  ExploreMatchesRoute: ExploreMatchesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MatchesReadyRoute: MatchesReadyRoute,
  MyProfileRoute: MyProfileRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  ProfileSetupStep2Route: ProfileSetupStep2Route,
  QuestionRoute: QuestionRoute,
  QuestionnaireHubRoute: QuestionnaireHubRoute,
  QuestionnaireIntroRoute: QuestionnaireIntroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StudentProfileRoute: StudentProfileRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
