/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreMatchesRouteImport } from './routes/explore-matches'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchesReadyRouteImport } from './routes/matches-ready'
import { Route as QuestionRouteImport } from './routes/question'
import { Route as QuestionnaireHubRouteImport } from './routes/questionnaire-hub'
import { Route as QuestionnaireIntroRouteImport } from './routes/questionnaire-intro'
import { Route as SignupRouteImport } from './routes/signup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreMatchesRoute = ExploreMatchesRouteImport.update({
  id: '/explore-matches',
  path: '/explore-matches',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesReadyRoute = MatchesReadyRouteImport.update({
  id: '/matches-ready',
  path: '/matches-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionRoute = QuestionRouteImport.update({
  id: '/question',
  path: '/question',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireHubRoute = QuestionnaireHubRouteImport.update({
  id: '/questionnaire-hub',
  path: '/questionnaire-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireIntroRoute = QuestionnaireIntroRouteImport.update({
  id: '/questionnaire-intro',
  path: '/questionnaire-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore-matches': typeof ExploreMatchesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/matches-ready': typeof MatchesReadyRoute
  '/question': typeof QuestionRoute
  '/questionnaire-hub': typeof QuestionnaireHubRoute
  '/questionnaire-intro': typeof QuestionnaireIntroRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore-matches': typeof ExploreMatchesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/matches-ready': typeof MatchesReadyRoute
  '/question': typeof QuestionRoute
  '/questionnaire-hub': typeof QuestionnaireHubRoute
  '/questionnaire-intro': typeof QuestionnaireIntroRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore-matches': typeof ExploreMatchesRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/matches-ready': typeof MatchesReadyRoute
  '/question': typeof QuestionRoute
  '/questionnaire-hub': typeof QuestionnaireHubRoute
  '/questionnaire-intro': typeof QuestionnaireIntroRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore-matches'
    | '/home'
    | '/login'
    | '/matches-ready'
    | '/question'
    | '/questionnaire-hub'
    | '/questionnaire-intro'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore-matches'
    | '/home'
    | '/login'
    | '/matches-ready'
    | '/question'
    | '/questionnaire-hub'
    | '/questionnaire-intro'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/explore-matches'
    | '/home'
    | '/login'
    | '/matches-ready'
    | '/question'
    | '/questionnaire-hub'
    | '/questionnaire-intro'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreMatchesRoute: typeof ExploreMatchesRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MatchesReadyRoute: typeof MatchesReadyRoute
  QuestionRoute: typeof QuestionRoute
  QuestionnaireHubRoute: typeof QuestionnaireHubRoute
  QuestionnaireIntroRoute: typeof QuestionnaireIntroRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-matches': {
      id: '/explore-matches'
      path: '/explore-matches'
      fullPath: '/explore-matches'
      preLoaderRoute: typeof ExploreMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches-ready': {
      id: '/matches-ready'
      path: '/matches-ready'
      fullPath: '/matches-ready'
      preLoaderRoute: typeof MatchesReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question': {
      id: '/question'
      path: '/question'
      fullPath: '/question'
      preLoaderRoute: typeof QuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-hub': {
      id: '/questionnaire-hub'
      path: '/questionnaire-hub'
      fullPath: '/questionnaire-hub'
      preLoaderRoute: typeof QuestionnaireHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire-intro': {
      id: '/questionnaire-intro'
      path: '/questionnaire-intro'
      fullPath: '/questionnaire-intro'
      preLoaderRoute: typeof QuestionnaireIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreMatchesRoute: ExploreMatchesRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MatchesReadyRoute: MatchesReadyRoute,
  QuestionRoute: QuestionRoute,
  QuestionnaireHubRoute: QuestionnaireHubRoute,
  QuestionnaireIntroRoute: QuestionnaireIntroRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
